apiVersion: v1
kind: Secret
metadata:
  name: argo-ci-token
  namespace: argocd
  annotations:
    kubernetes.io/service-account.name: argo-ci
type: kubernetes.io/service-account-token


# Method 1: Use kubectl to trigger sync
kubectl patch application <app-name> -n argocd \
  -p '{"operation":{"sync":{"prune":true}}}' --type=merge

# Method 2: Sync specific resource using kubectl
kubectl patch application <app-name> -n argocd \
  -p '{"operation":{"sync":{"resources":[{"kind":"Rollout","name":"<app-name>","namespace":"<namespace>"}]}}}' --type=merge

# Method 3: Use ArgoCD API directly
curl -X POST \
  -H "Authorization: Bearer $ARGOCD_AUTH_TOKEN" \
  -H "Content-Type: application/json" \
  https://your-argocd-server.com/api/v1/applications/<app-name>/sync
