apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/applogs-presistentvolumeclaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-app2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
