namespace: amazon-cloudwatch

serviceAccount:
  create: true
  name: fluent-bit

clusterRole:
  create: true
  name: fluent-bit

daemonset:
  name: fluent-bit

fluentbit:
  image:
    repository: fluent/fluent-bit
    tag: 1.8.3
    pullPolicy: IfNotPresent

  volumes:
    - name: data-history
      mountPath: /var/data/history
      pvc: history-pvc
      path: /var/data/history/*.logs

    - name: data-authlog
      mountPath: /var/data/authlog
      pvc: authlog-pvc
      path: /var/data/authlog/*.log

    - name: data-apphistory
      mountPath: /var/data/apphistory
      pvc: apphistory-pvc
      path: /var/data/apphistory/*.log

  config:
    filters: |
      [FILTER]
          Name              kubernetes
          Match             *
          Merge_Log         On
          Merge_Log_Key     log_processed
          K8S-Logging.Parser On
          K8S-Logging.Exclude Off

    outputs: |
      [OUTPUT]
          Name              cloudwatch
          Match             *
          region            us-west-2
          log_group_name    fluent-bit-log-group
          log_stream_prefix from-fluent-bit-
          auto_create_group true
