apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.daemonset.name }}-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    {{- range .Values.fluentbit.volumes }}
    [INPUT]
        Name              tail
        Path              {{ .path }}
        Path_Key          {{ .name }}_log_path
        Tag               {{ .name }}.*
        DB                /var/log/flb_{{ .name }}.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    {{- end }}

{{ .Values.fluentbit.config.filters | indent 4 }}

{{ .Values.fluentbit.config.outputs | indent 4 }}
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
