apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/history/archiver/Log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-app1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
