apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.daemonset.name }}-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

{{ .Values.fluentbit.config.inputs | indent 4 }}

{{ .Values.fluentbit.config.filters | indent 4 }}

{{ .Values.fluentbit.config.outputs | indent 4 }}
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
