apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonset.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.daemonset.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.daemonset.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: fluent-bit
        image: "{{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}"
        imagePullPolicy: {{ .Values.fluentbit.image.pullPolicy }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: config
          mountPath: /fluent-bit/etc/
        {{- range .Values.fluentbit.volumes }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: config
        configMap:
          name: {{ .Values.daemonset.name }}-config
      {{- range .Values.fluentbit.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .pvc }}
      {{- end }}
