# fluent-bit/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: fluent-bit
  apiGroup: rbac.authorization.k8s.io