# fluent-bit/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluent-bit.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: {{ .Values.fluentbit.config.inputs | quote }}
  filters.conf: {{ .Values.fluentbit.config.filters | quote }}
  outputs.conf: {{ .Values.fluentbit.config.outputs | quote }}