# values.yaml
namespace: amazon-cloudwatch

image:
  repository: amazon/aws-for-fluent-bit
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

serviceAccount:
  create: true
  name: fluentbit

cloudWatch:
  region: us-west-2
  logGroupName: /aws/eks/fluentbit-logs
  logStreamPrefix: ${HOST_NAME}-

additionalVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: app-logs
    mountPath: /data
    readOnly: true

additionalVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: app-logs
    hostPath:
      path: /data 