# fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: {{ .Values.namespace }}
  annotations:
    {{- if .Values.fluentbit.existingIamRole.arn }}
    eks.amazonaws.com/role-arn: {{ .Values.fluentbit.existingIamRole.arn }}
    {{- end }}