# fluent-bit/values.yaml

namespace: amazon-cloudwatch

fluentbit:
  enabled: true
  service:
    enabled: true
    type: ClusterIP
    annotations: {}

  replicas: 1  # Number of Fluent Bit instances to run

  config:
    inputs: |
      [INPUT]
          Name              tail
          Tag               log-gen-app.*
          Path              /data/history/*.logs
          Path              /data/authlog/*.log
          Path              /data/history/*.log
          DB                /var/log/flb_kube.db
          Mem_Buf_Limit     5MB
          Skip_Long_Lines   On
          Refresh_Interval   10

    filters: |
      [FILTER]
          Name              kubernetes
          Match             log-gen-app.*
          Kube_URL          https://kubernetes.default.svc.cluster.local:443
          Merge_Log         On
          Keep_Log          On

    outputs: |
      [OUTPUT]
          Name              cloudwatch
          Match             *
          region            us-east-1
          log_group_name    /aws/eks/log-gen-app
          log_stream_prefix fluentbit-
          auto_create_group true
          log_stream_name   {instance_id}

  additionalInputs: []
  additionalFilters: []
  additionalOutputs: []
  additionalParsers: []

  existingIamRole:
    arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<IAM_ROLE_NAME>

  persistentVolumes:
    - name: history-logs
      claimName: history-logs-pvc
      mountPath: /data/history
    - name: authlog
      claimName: authlog-pvc
      mountPath: /data/authlog
    - name: additional-logs
      claimName: additional-logs-pvc
      mountPath: /data/additional

  daemonset:
    enabled: false  # Disable DaemonSet since we're using Deployment
    updateStrategy:
      type: RollingUpdate
    nodeSelector: {}
    tolerations: []
    affinity: {}
