name: Production Release - Tag & Notes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  create-release:
    name: Create Production Git Tag and Release Notes
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version and tag name
        id: tag
        run: |
          version="${{ github.event.inputs.version }}"
          if [[ -z "$version" ]]; then
            echo "Version input is required!" >&2
            exit 1
          fi
          tag="v$version"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.tag.outputs.tag }}
          git push origin ${{ steps.tag.outputs.tag }}

      - name: Generate release notes
        id: changelog
        run: |
          version="${{ steps.tag.outputs.version }}"
          tag="${{ steps.tag.outputs.tag }}"
          branch="${GITHUB_REF_NAME}"

          echo "# Release ${version} (${branch})" > release_notes.md
          echo "" >> release_notes.md
          echo "**Tag:** \`${tag}\`" >> release_notes.md
          echo "**Branch:** \`${branch}\`" >> release_notes.md
          echo "**Release Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> release_notes.md
          echo "" >> release_notes.md

          echo "## 📋 Changes" >> release_notes.md
          echo "" >> release_notes.md

          prev_tag=$(git tag --sort=-creatordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | grep -v "^$tag$" | head -n1)
          if [ -z "$prev_tag" ]; then
            echo "### Initial Production Release" >> release_notes.md
            echo "" >> release_notes.md
            git log --pretty=format:"- **%s** (%h) - %an" >> release_notes.md
          else
            echo "### Changes since ${prev_tag}" >> release_notes.md
            echo "" >> release_notes.md
            git log "$prev_tag..$tag" --pretty=format:"- **%s** (%h) - %an" >> release_notes.md
          fi

          echo "" >> release_notes.md
          echo "---" >> release_notes.md
          echo "*This release was automatically generated by GitHub Actions*" >> release_notes.md

      - name: Create new release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.version }}
          body_path: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update GitHub Wiki with pipeline run details
        run: |
          set -e
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone "https://x-access-token:${{ secrets.GH_WIKI_TOKEN }}@github.com/${{ github.repository }}.wiki.git" wiki
          cd wiki

          WIKI_PAGE="Release-History.md"
          RUNNER="${{ github.actor }}"
          RUN_DATE="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          VERSION="${{ steps.tag.outputs.version }}"
          TAG="${{ steps.tag.outputs.tag }}"
          BRANCH="${GITHUB_REF_NAME}"
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Prepare new entry
          NEW_ENTRY="| $RUN_DATE | $RUNNER | $VERSION | $TAG | $BRANCH | [Run]($RUN_URL) |"

          # Create page if not exists
          if [ ! -f "$WIKI_PAGE" ]; then
        echo "# Release History" > "$WIKI_PAGE"
        echo "" >> "$WIKI_PAGE"
        echo "| Date | User | Version | Tag | Branch | Workflow Run |" >> "$WIKI_PAGE"
        echo "|------|------|---------|-----|--------|--------------|" >> "$WIKI_PAGE"
        echo "$NEW_ENTRY" >> "$WIKI_PAGE"
          else
        # Insert new entry after the header (line 4)
        awk -v new_entry="$NEW_ENTRY" 'NR==1{print;next} NR==2{print;next} NR==3{print;next} NR==4{print; print new_entry; next} {print}' "$WIKI_PAGE" > tmp && mv tmp "$WIKI_PAGE"
          fi

          git add "$WIKI_PAGE"
          git commit -m "Update release history for $VERSION"
          git push origin master
        env:
          GH_WIKI_TOKEN: ${{ secrets.GH_WIKI_TOKEN }}