name: Sync App Release Tag to Helm Chart Repo

on:
  push:
    branches:
      - develop
      - qa
      - production
  workflow_dispatch:

jobs:
  create-release:
    name: Auto Create Git Tag and Release Notes
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag (if any)
        id: get-latest-tag
        run: |
          latest_tag=$(git tag --sort=-creatordate | head -n1)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Get new version tag with git SHA
        id: new-tag
        run: |
          branch="${GITHUB_REF_NAME}"
          git_sha=$(git rev-parse --short HEAD)
          
          # Find the latest tag for this branch matching the pattern
          latest_tag=$(git tag --list "${branch}-*" | sort -V | tail -n1)
          if [[ -z "$latest_tag" ]]; then
            # If no tag exists, start with 0.1.0
            new_version="0.1.0"
          else
            # Extract the version part (after the branch-)
            version="${latest_tag#${branch}-}"
            # Remove git SHA suffix if present
            version="${version%_*}"
            # Split version into parts
            IFS='.' read -r major minor patch <<< "$version"
            # Increment patch
            patch=$((patch + 1))
            new_version="${major}.${minor}.${patch}"
          fi
          new_tag="${branch}-${new_version}_${git_sha}"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
          echo "version=$new_version" >> $GITHUB_OUTPUT
          echo "git_sha=$git_sha" >> $GITHUB_OUTPUT

      - name: Generate pretty release notes
        id: changelog
        run: |
          latest_tag="${{ steps.get-latest-tag.outputs.latest_tag }}"
          version="${{ steps.new-tag.outputs.version }}"
          git_sha="${{ steps.new-tag.outputs.git_sha }}"
          branch="${GITHUB_REF_NAME}"
          
          # Create header
          echo "# Release ${version} (${branch})" > release_notes.md
          echo "" >> release_notes.md
          echo "**Git SHA:** \`${git_sha}\`" >> release_notes.md
          echo "**Branch:** \`${branch}\`" >> release_notes.md
          echo "**Release Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> release_notes.md
          echo "" >> release_notes.md
          
          # Add changes section
          echo "## 📋 Changes" >> release_notes.md
          echo "" >> release_notes.md
          
          if [ -z "$latest_tag" ]; then
            echo "### Initial Release" >> release_notes.md
            echo "" >> release_notes.md
            git log --pretty=format:"- **%s** (%h) - %an" --no-merges >> release_notes.md
          else
            echo "### Changes since ${latest_tag}" >> release_notes.md
            echo "" >> release_notes.md
            git log "$latest_tag"..HEAD --pretty=format:"- **%s** (%h) - %an" --no-merges >> release_notes.md
          fi
          
          echo "" >> release_notes.md
          echo "---" >> release_notes.md
          echo "*This release was automatically generated by GitHub Actions*" >> release_notes.md
          
          # Convert to GitHub output format
          changelog=$(cat release_notes.md)
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "changelog=$changelog" >> $GITHUB_OUTPUT

      - name: Create new release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.new-tag.outputs.new_tag }}
          name: Release ${{ steps.new-tag.outputs.version }} (${{ steps.new-tag.outputs.git_sha }})
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
